from wazimap.data.tables import FieldTable

FieldTable(['Population_Sex'])
FieldTable(['Population_Residence'])
FieldTable(['candidate'], id="votes_per_candidate")
FieldTable(['votes'], id="valid_invalid_votes")
FieldTable(['voters'], id="registered_accredited_voters")
FieldTable(['crops'], id='food_production', value_type='Float')
FieldTable(['centers'], id="health_centers")
FieldTable(['centers'], id="hiv_health_centers")
FieldTable(['organization_type'], id="health_centers_ownership")
FieldTable(['workers'], id="health_workers")
FieldTable(['causes_of_death_over_five'])
FieldTable(['causes_of_death_under_five'])
FieldTable(['inpatient_diagnosis_over_five'])
FieldTable(['inpatient_diagnosis_under_five'])
FieldTable(['outpatient_diagnosis_over_five'])
FieldTable(['outpatient_diagnosis_under_five'])