# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hurumap', '0004_auto_20180609_1828'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wazimap', '0008_auto_20170424_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wazimap.Geography')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ReportSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicPageTopicDataIndicators',
            fields=[
                ('dataindicator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hurumap.DataIndicator')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalManyToManyField(related_name='topic_data_indicators', to='takwimu.TopicPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('hurumap.dataindicator', models.Model),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='indicators',
            field=models.ManyToManyField(to='hurumap.DataIndicator'),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='parent_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='takwimu.TopicPage'),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='related_topics',
            field=models.ManyToManyField(related_name='_topicpage_related_topics_+', to='takwimu.TopicPage'),
        ),
        migrations.AddField(
            model_name='reportsectionpage',
            name='topics',
            field=models.ManyToManyField(to='takwimu.TopicPage'),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='topics',
            field=models.ManyToManyField(to='takwimu.TopicPage'),
        ),
    ]
