# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0004_auto_20180609_1828'),
        ('takwimu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPageDataIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurumap.DataIndicator')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='topicpagetopicdataindicators',
            name='dataindicator_ptr',
        ),
        migrations.RemoveField(
            model_name='topicpagetopicdataindicators',
            name='page',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='indicators',
        ),
        migrations.DeleteModel(
            name='TopicPageTopicDataIndicators',
        ),
        migrations.AddField(
            model_name='topicpagedataindicators',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_page_data_indicators', to='takwimu.TopicPage'),
        ),
    ]
