# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 13:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0002_auto_20180610_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpagedataindicators',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_indicators', to='takwimu.TopicPage'),
        ),
    ]
