# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-17 20:05
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0003_auto_20180617_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportpagesections',
            old_name='page',
            new_name='report_page',
        ),
    ]
