# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-23 14:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0004_auto_20180617_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportPage',
            new_name='ProfilePage',
        ),
        migrations.RenameModel(
            old_name='ReportPageSections',
            new_name='ProfilePageSections',
        ),
        migrations.RenameModel(
            old_name='ReportPageTopics',
            new_name='ProfilePageTopics',
        ),
        migrations.RenameModel(
            old_name='ReportSectionPage',
            new_name='ProfileSectionPage',
        ),
        migrations.RenameModel(
            old_name='ReportSectionPageTopics',
            new_name='ProfileSectionPageTopics',
        ),
        migrations.RenameField(
            model_name='profilepagesections',
            old_name='report_page',
            new_name='profile_page',
        ),
        migrations.RenameField(
            model_name='profilepagetopics',
            old_name='report_page',
            new_name='profile_page',
        ),
    ]
