# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0005_auto_20180610_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPageTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reportpage',
            name='topics',
        ),
        migrations.AddField(
            model_name='reportpagetopics',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='takwimu.ReportPage'),
        ),
        migrations.AddField(
            model_name='reportpagetopics',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takwimu.TopicPage'),
        ),
    ]
