# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-30 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0005_auto_20180623_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpage',
            name='description_am',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
