# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-02 06:46
from __future__ import unicode_literals

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0005_auto_20180623_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpage',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
