# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0005_auto_20180623_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpagedataindicators',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
