# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0007_auto_20180610_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPageSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='takwimu.ReportPage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takwimu.ReportSectionPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
