# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-02 12:47
from __future__ import unicode_literals

from django.db import migrations
import takwimu.models.dashboard
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0008_auto_20180702_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'topic', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'icon', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'summary', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), (b'indicators', wagtail.wagtailcore.blocks.ListBlock(takwimu.models.dashboard.DataIndicatorChooserBlock(), required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='profilesectionpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'topic', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'icon', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'summary', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), (b'indicators', wagtail.wagtailcore.blocks.ListBlock(takwimu.models.dashboard.DataIndicatorChooserBlock(), required=False))]))], blank=True),
        ),
    ]
