# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-02 12:47
from django.db import migrations
import takwimu.models.dashboard
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0008_auto_20180702_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='body',
            field=wagtail.core.fields.StreamField([(b'topic', wagtail.core.blocks.StructBlock([(b'title', wagtail.core.blocks.CharBlock(required=False)), (b'icon', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'summary', wagtail.core.blocks.TextBlock(required=False)), (b'body', wagtail.core.blocks.RichTextBlock(required=False)), (b'indicators', wagtail.core.blocks.ListBlock(takwimu.models.dashboard.DataIndicatorChooserBlock(), required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='profilesectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([(b'topic', wagtail.core.blocks.StructBlock([(b'title', wagtail.core.blocks.CharBlock(required=False)), (b'icon', wagtail.images.blocks.ImageChooserBlock(required=False)), (b'summary', wagtail.core.blocks.TextBlock(required=False)), (b'body', wagtail.core.blocks.RichTextBlock(required=False)), (b'indicators', wagtail.core.blocks.ListBlock(takwimu.models.dashboard.DataIndicatorChooserBlock(), required=False))]))], blank=True),
        ),
    ]
