# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-03 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0009_auto_20180702_1547'),
        ('takwimu', '0006_auto_20180630_1524'),
    ]

    operations = [
    ]
