# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-04 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields
import takwimu.models.dashboard
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0009_auto_20180702_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('title', models.TextField()),
                ('benefit', wagtail.wagtailcore.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'topic', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'icon', takwimu.models.dashboard.IconChoiceBlock(required=False)), (b'summary', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), (b'indicators', wagtail.wagtailcore.blocks.StreamBlock([(b'free_form', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'snippet')), (b'data_indicator', takwimu.models.dashboard.DataIndicatorChooserBlock()), (b'embed', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'media')), (b'document', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'doc-full')), (b'image', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'caption', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'image')), (b'html', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'code')), (b'entities', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'entities', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'description', wagtail.wagtailcore.blocks.TextBlock(required=False))]))), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'group'))], required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='profilesectionpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'topic', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'icon', takwimu.models.dashboard.IconChoiceBlock(required=False)), (b'summary', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), (b'indicators', wagtail.wagtailcore.blocks.StreamBlock([(b'free_form', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'snippet')), (b'data_indicator', takwimu.models.dashboard.DataIndicatorChooserBlock()), (b'embed', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'media')), (b'document', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'doc-full')), (b'image', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'caption', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'image')), (b'html', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(required=False)), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'code')), (b'entities', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'entities', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'description', wagtail.wagtailcore.blocks.TextBlock(required=False))]))), (b'source', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'source_date', wagtail.wagtailcore.blocks.DateBlock(required=False))], icon=b'group'))], required=False))]))], blank=True),
        ),
    ]
