# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-04 12:40
from django.db import migrations, models
import fontawesome.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0010_auto_20180704_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('title', models.TextField()),
                ('benefit', wagtail.core.fields.RichTextField()),
            ],
        ),
    ]
