# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-04 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0012_auto_20180704_2028'),
        ('takwimu', '0011_supportservice'),
    ]

    operations = [
    ]
