# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-04 17:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0013_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportservice',
            old_name='benefit',
            new_name='description',
        ),
    ]
