# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-07 15:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0015_aboutpage_contactuspage_keycontacts_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepagetopics',
            name='profile_page',
        ),
        migrations.RemoveField(
            model_name='profilepagetopics',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='profilesectionpagetopics',
            name='section_page',
        ),
        migrations.RemoveField(
            model_name='profilesectionpagetopics',
            name='topic',
        ),
        migrations.DeleteModel(
            name='ProfilePageTopics',
        ),
        migrations.DeleteModel(
            name='ProfileSectionPageTopics',
        ),
    ]
