# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-09 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0016_auto_20180707_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainerSteps',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sidebar', wagtail.wagtailcore.fields.RichTextField()),
                ('steps', wagtail.wagtailcore.fields.StreamField([(b'step', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'brief', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'color', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Background colour.', required=False)), (b'body', wagtail.wagtailcore.blocks.RichTextBlock(required=False))], icon=b'user'))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
