# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-09 18:55
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0018_auto_20180709_1604'),
        ('takwimu', '0017_explainersteps'),
    ]

    operations = [
    ]
