# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0019_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to=b'testimonials/')),
            ],
        ),
    ]
