# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0020_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text=b'TAKWIMU Facebook page URL', null=True)),
                ('github', models.URLField(blank=True, help_text=b'TAKWIMU Github page URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text=b'TAKWIMU Instagram account URL', max_length=255, null=True)),
                ('medium', models.URLField(blank=True, help_text=b'TAKWIMU Medium page URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text=b'TAKWIMU Twitter account URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text=b'TAKWIMU YouTube channel or account URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='SupportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.EmailField(blank=True, help_text=b'TAKWIMU main email address', max_length=254, null=True)),
                ('zendesk', models.URLField(blank=True, help_text=b'TAKWIMU Zendesk account URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Support',
            },
        ),
    ]
