# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0020_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text=b'Facebook page URL', null=True)),
                ('instagram', models.URLField(help_text=b'Instagram Page URL', null=True)),
                ('youtube', models.URLField(help_text=b'YouTube channel URL', null=True)),
                ('twitter', models.URLField(help_text=b'Twitter URL', null=True)),
                ('medium', models.URLField(help_text=b'Medium Blog URL', null=True)),
                ('github', models.URLField(help_text=b'GitHub URL', null=True)),
                ('contact_email', models.URLField(help_text=b'Primary Contact Email')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Social Media Accounts',
            },
        ),
    ]
