# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-17 08:38
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0022_supportsetting_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', wagtail.core.fields.RichTextField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'About Us',
            },
        ),
    ]
