# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-17 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0023_aboutussetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('description', wagtail.core.fields.RichTextField()),
                ('category', models.CharField(choices=[(b'Standard', b'Standard'), (b'Premium', b'Premium')], default=b'Standard', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SupportService',
        ),
    ]
