# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-23 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0025_auto_20180720_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[(b'Standard', b'Standard'), (b'Premium', b'Premium'), (b'Persona', b'Persona')], default=b'Standard', max_length=20),
        ),
    ]
