# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-23 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0025_legalnoticesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalnoticesetting',
            name='site',
        ),
        migrations.DeleteModel(
            name='LegalNoticeSetting',
        ),
    ]
