# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-23 18:33
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('takwimu', '0026_auto_20180723_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
