# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-23 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0026_auto_20180723_1557'),
        ('takwimu', '0025_auto_20180720_0724'),
    ]

    operations = [
    ]
