# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-24 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0027_merge'),
        ('takwimu', '0027_service_cover'),
    ]

    operations = [
    ]
