# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-24 10:11
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0028_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explainersteps',
            name='steps',
            field=wagtail.core.fields.StreamField([(b'step', wagtail.core.blocks.StructBlock([(b'title', wagtail.core.blocks.CharBlock(required=False)), (b'brief', wagtail.core.blocks.TextBlock(required=False)), (b'color', wagtail.core.blocks.CharBlock(help_text=b'Background colour.', required=False)), (b'body', wagtail.core.blocks.RichTextBlock(required=False)), (b'sidebar', wagtail.core.blocks.RichTextBlock(required=False))], icon=b'user'))]),
        ),
    ]
