# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-25 15:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0029_auto_20180724_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsetting',
            name='community',
            field=models.URLField(blank=True, help_text=b'TAKWIMU Community forums URL', null=True),
        ),
    ]
