# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-30 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0030_supportsetting_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='geo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wazimap.Geography'),
        ),
    ]
