# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-27 12:05
from django.db import migrations, models
import django.db.models.deletion
import takwimu.models.dashboard
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0030_supportsetting_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportServicesSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', wagtail.core.fields.StreamField([(b'service', wagtail.core.blocks.StructBlock([(b'title', wagtail.core.blocks.CharBlock(required=True)), (b'icon', takwimu.models.dashboard.IconChoiceBlock(required=False)), (b'cover', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=b'+', required=False)), (b'description', wagtail.core.blocks.RichTextBlock(required=True)), (b'category', wagtail.core.blocks.ChoiceBlock(choices=[(b'Standard', b'Standard'), (b'Premium', b'Premium'), (b'Persona', b'Persona')], max_length=20))]))], blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Support Services',
            },
        ),
    ]
