# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-30 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0031_auto_20180730_1215'),
        ('takwimu', '0031_supportservicessetting'),
    ]

    operations = [
    ]
