# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-30 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0032_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cover',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
