# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-27 08:42
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0034_profilepage_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasetting',
            name='linkedin',
            field=models.URLField(blank=True, help_text=b'TAKWIMU LinkedIn account URL', max_length=255, null=True),
        ),
    ]
