# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-29 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0035_faqsetting'),
        ('takwimu', '0035_socialmediasetting_linkedin'),
    ]

    operations = [
    ]
