# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-30 05:56
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0035_socialmediasetting_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqs', wagtail.core.fields.StreamField([(b'faq', wagtail.core.blocks.StructBlock([(b'question', wagtail.core.blocks.CharBlock(required=True)), (b'answer', wagtail.core.blocks.RichTextBlock(required=True)), (b'cta_one_url', wagtail.core.blocks.URLBlock(default=b'https://takwimu.zendesk.com/', label=b"'Find Out More' Button URL")), (b'cta_two_name', wagtail.core.blocks.CharBlock(label=b'Second Button Name (Optional)', required=False)), (b'cta_two_url', wagtail.core.blocks.URLBlock(label=b'Second Button URL (Optional)', required=False))]))], blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'FAQ',
            },
        ),
    ]
