# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-29 13:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0036_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqsetting',
            name='faqs',
            field=wagtail.wagtailcore.fields.StreamField([(b'faq', wagtail.wagtailcore.blocks.StructBlock([(b'question', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'answer', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), (b'cta_one_url', wagtail.wagtailcore.blocks.URLBlock(default=b'https://takwimu.zendesk.com/', label=b"'Find Out More' button URL")), (b'cta_two_name', wagtail.wagtailcore.blocks.CharBlock(label=b'Second button Name (optional)', required=False)), (b'cta_two_url', wagtail.wagtailcore.blocks.URLBlock(label=b'Second button URL (optional)', required=False))]))], blank=True),
        ),
    ]
