# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-30 12:44
from django.db import migrations

from takwimu.utils import db

FAQ_SETTING_FILENAME = 'faqsetting.json'


def load_fixture(apps, schema_editor):
    db.migrate_fixture(apps, FAQ_SETTING_FILENAME)


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0036_faqsetting'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
