# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0039_auto_20180925_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPublishSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenya', models.BooleanField(default=False)),
                ('nigeria', models.BooleanField(default=False)),
                ('tanzania', models.BooleanField(default=False)),
                ('uganda', models.BooleanField(default=False)),
                ('drc', models.BooleanField(default=False)),
                ('ethiopia', models.BooleanField(default=False)),
                ('burkina_faso', models.BooleanField(default=False)),
                ('senegal', models.BooleanField(default=False)),
                ('south_africa', models.BooleanField(default=False)),
                ('zambia', models.BooleanField(default=False)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
