# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 12:19
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0041_countryprofilessetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypublishsetting',
            name='site',
        ),
        migrations.DeleteModel(
            name='CountryPublishSetting',
        ),
    ]
