# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 10:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0043_topicblock_widget_sdg'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsetting',
            name='support',
            field=models.EmailField(blank=True, help_text=b'TAKWIMU support email address', max_length=254, null=True),
        ),
    ]
