# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('takwimu', '0044_supportsetting_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='promotion_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='tweet_creator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='twitter_card',
            field=models.CharField(blank=True, choices=[(b'summary', b'Summary'), (b'summary_large_image', b'Summary with image'), (b'player', b'Media player'), (b'app', b'Link to download app')], max_length=255),
        ),
        migrations.AddField(
            model_name='profilesectionpage',
            name='promotion_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='profilesectionpage',
            name='tweet_creator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilesectionpage',
            name='twitter_card',
            field=models.CharField(blank=True, choices=[(b'summary', b'Summary'), (b'summary_large_image', b'Summary with image'), (b'player', b'Media player'), (b'app', b'Link to download app')], max_length=255),
        ),
    ]
