# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import takwimu.models.dashboard
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0046_profilepage_summary_richtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='BF',
            field=models.BooleanField(default=True, verbose_name='Burkina Faso'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='CD',
            field=models.BooleanField(default=True, verbose_name='Congo, the Democratic Republic of the'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='ET',
            field=models.BooleanField(default=True, verbose_name='Ethiopia'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='KE',
            field=models.BooleanField(default=True, verbose_name='Kenya'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='NG',
            field=models.BooleanField(default=True, verbose_name='Nigeria'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='SN',
            field=models.BooleanField(default=True, verbose_name='Senegal'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='TZ',
            field=models.BooleanField(default=True, verbose_name='Tanzania, United Republic of'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='UG',
            field=models.BooleanField(default=False, verbose_name='Uganda'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='ZA',
            field=models.BooleanField(default=True, verbose_name='South Africa'),
        ),
        migrations.AlterField(
            model_name='countryprofilessetting',
            name='ZM',
            field=models.BooleanField(default=False, verbose_name='Zambia'),
        ),
        migrations.AlterField(
            model_name='explainersteps',
            name='steps',
            field=wagtail.core.fields.StreamField([('step', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('brief', wagtail.core.blocks.TextBlock(required=False)), ('color', wagtail.core.blocks.CharBlock(help_text='Background colour.', required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('sidebar', wagtail.core.blocks.RichTextBlock(required=False))], icon='user'))]),
        ),
        migrations.AlterField(
            model_name='faq',
            name='cta_one_url',
            field=models.URLField(default='https://takwimu.zendesk.com/', verbose_name="'Find Out More' button URL"),
        ),
        migrations.AlterField(
            model_name='faq',
            name='cta_two_name',
            field=models.TextField(blank=True, verbose_name='Second button Name (optional)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='cta_two_url',
            field=models.URLField(blank=True, verbose_name='Second button URL (optional)'),
        ),
        migrations.AlterField(
            model_name='faqsetting',
            name='faqs',
            field=wagtail.core.fields.StreamField([('faq', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(required=True)), ('answer', wagtail.core.blocks.RichTextBlock(required=True)), ('cta_one_url', wagtail.core.blocks.URLBlock(default='https://takwimu.zendesk.com/', label="'Find Out More' Button URL")), ('cta_two_name', wagtail.core.blocks.CharBlock(label='Second Button Name (Optional)', required=False)), ('cta_two_url', wagtail.core.blocks.URLBlock(label='Second Button URL (Optional)', required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='body',
            field=wagtail.core.fields.StreamField([('topic', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('icon', takwimu.models.dashboard.IconChoiceBlock(required=False)), ('summary', wagtail.core.blocks.RichTextBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('indicators', wagtail.core.blocks.StreamBlock([('indicators', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('widgets', wagtail.core.blocks.StreamBlock([('free_form', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='snippet', template='takwimu/_includes/dataview/freeform.html')), ('embed', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('embed', wagtail.embeds.blocks.EmbedBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='media', template='takwimu/_includes/dataview/embed.html')), ('document', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='doc-full', template='takwimu/_includes/dataview/document.html')), ('image', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.TextBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='image', template='takwimu/_includes/dataview/image.html')), ('html', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('raw_html', wagtail.core.blocks.RawHTMLBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='code', template='takwimu/_includes/dataview/code.html')), ('hurumap', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('data_country', wagtail.core.blocks.ChoiceBlock(choices=[('ET', 'Ethiopia'), ('KE', 'Kenya'), ('NG', 'Nigeria'), ('SN', 'Senegal'), ('TZ', 'Tanzania')], label='Country')), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('data_id', wagtail.core.blocks.ChoiceBlock(choices=[('demographics-residence_dist', 'Population by Residence'), ('demographics-sex_dist', 'Population by Sex'), ('crops-crop_distribution', 'Crops Produced'), ('health_centers-prevention_methods_dist', 'Knowledge of HIV Prevention Methods'), ('education-education_reached_distribution', 'Highest Level of Education Attained'), ('education-school_attendance_distribution', 'School Attendance by Sex'), ('donors-donor_assistance_dist', 'Principal Donors'), ('poverty-poverty_residence_dist', 'Percentage of Population living in Poverty by Residence'), ('poverty-poverty_age_dist', 'Percentage of Population living in Poverty by Age and Residence'), ('fgm-fgm_age_dist', 'Percentage of Women that have undergone FGM by Age'), ('security-seized_firearms_dist', 'Seized Firearms'), ('donors-donor_programmes_dist', 'Donor Funded Programmes'), ('budget-government_expenditure_dist', 'Government Expenditure'), ('health_centers-health_centers_dist', 'Number of health centers by type')], label='Data')), ('chart_type', wagtail.core.blocks.ChoiceBlock(choices=[('histogram', 'Histogram'), ('pie', 'Pie Chart'), ('grouped_column', 'Grouped Column')], label='Chart Type')), ('data_stat_type', wagtail.core.blocks.ChoiceBlock(choices=[('percentage', 'Percentage'), ('scaled-percentage', 'Scaled Percentage'), ('dollar', 'Dollar')], label='Stat Type')), ('data_source_link', wagtail.core.blocks.URLBlock(label='Source URL', required=False)), ('data_source_title', wagtail.core.blocks.CharBlock(label='Source Title', required=False)), ('chart_qualifier', wagtail.core.blocks.RichTextBlock(features=['h5', 'h6', 'ol', 'ul', 'bold', 'italic', 'hr', 'link'], help_text='Chart context e.g. legend, universe, etc.', label='Chart Qualifier', required=False)), ('chart_height', wagtail.core.blocks.IntegerBlock(help_text='Default is 300px', label='Chart Height', required=False)), ('widget_height', wagtail.core.blocks.IntegerBlock(help_text='Default is 450px', label='Widget Height', required=False))], icon='code', template='takwimu/_includes/dataview/hurumap.html')), ('entities', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('entities', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))]))), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='group', template='takwimu/_includes/dataview/entities.html'))], required=False))], required=False))], required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='twitter_card',
            field=models.CharField(blank=True, choices=[('summary', 'Summary'), ('summary_large_image', 'Summary with image'), ('player', 'Media player'), ('app', 'Link to download app')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profilesectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('topic', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('icon', takwimu.models.dashboard.IconChoiceBlock(required=False)), ('summary', wagtail.core.blocks.RichTextBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('indicators', wagtail.core.blocks.StreamBlock([('indicators', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('widgets', wagtail.core.blocks.StreamBlock([('free_form', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='snippet', template='takwimu/_includes/dataview/freeform.html')), ('embed', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('embed', wagtail.embeds.blocks.EmbedBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='media', template='takwimu/_includes/dataview/embed.html')), ('document', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='doc-full', template='takwimu/_includes/dataview/document.html')), ('image', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.TextBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='image', template='takwimu/_includes/dataview/image.html')), ('html', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('raw_html', wagtail.core.blocks.RawHTMLBlock(required=False)), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='code', template='takwimu/_includes/dataview/code.html')), ('hurumap', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('data_country', wagtail.core.blocks.ChoiceBlock(choices=[('ET', 'Ethiopia'), ('KE', 'Kenya'), ('NG', 'Nigeria'), ('SN', 'Senegal'), ('TZ', 'Tanzania')], label='Country')), ('sdg', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Please select an SDG'), ('no-poverty', 'No Poverty'), ('zero-hunger', 'Zero Hunger'), ('good-health-and-well-being', 'Good Health and Well-being'), ('quality-education', 'Quality Education'), ('gender-equality', 'Gender Equality'), ('clean-water-and-sanitation', 'Clean Water and Sanitation'), ('affordable-and-clean-energy', 'Affordable and Clean Energy'), ('decent-jobs-and-economic-growth', 'Decent Jobs and Economic Growth'), ('industry-innovation-and-infrastructure', 'Industry, Innovation and Infrastructure'), ('reduced-inequalities', 'Reduced Inequalities'), ('sustainable-cities-and-communities', 'Sustainable Cities and Communities'), ('responsible-consumption-and-production', 'Responsible Consumption and Production'), ('climate-action', 'Climate Action'), ('life-below-water', 'Life Below Water'), ('life-on-land', 'Life on Land'), ('peace-and-justice-strong-institutions', 'Peace and Justice - Strong Institutions'), ('partnerships-for-the-goals', 'Partnerships for the Goals')], label='SDG Goal', required=False)), ('data_id', wagtail.core.blocks.ChoiceBlock(choices=[('demographics-residence_dist', 'Population by Residence'), ('demographics-sex_dist', 'Population by Sex'), ('crops-crop_distribution', 'Crops Produced'), ('health_centers-prevention_methods_dist', 'Knowledge of HIV Prevention Methods'), ('education-education_reached_distribution', 'Highest Level of Education Attained'), ('education-school_attendance_distribution', 'School Attendance by Sex'), ('donors-donor_assistance_dist', 'Principal Donors'), ('poverty-poverty_residence_dist', 'Percentage of Population living in Poverty by Residence'), ('poverty-poverty_age_dist', 'Percentage of Population living in Poverty by Age and Residence'), ('fgm-fgm_age_dist', 'Percentage of Women that have undergone FGM by Age'), ('security-seized_firearms_dist', 'Seized Firearms'), ('donors-donor_programmes_dist', 'Donor Funded Programmes'), ('budget-government_expenditure_dist', 'Government Expenditure'), ('health_centers-health_centers_dist', 'Number of health centers by type')], label='Data')), ('chart_type', wagtail.core.blocks.ChoiceBlock(choices=[('histogram', 'Histogram'), ('pie', 'Pie Chart'), ('grouped_column', 'Grouped Column')], label='Chart Type')), ('data_stat_type', wagtail.core.blocks.ChoiceBlock(choices=[('percentage', 'Percentage'), ('scaled-percentage', 'Scaled Percentage'), ('dollar', 'Dollar')], label='Stat Type')), ('data_source_link', wagtail.core.blocks.URLBlock(label='Source URL', required=False)), ('data_source_title', wagtail.core.blocks.CharBlock(label='Source Title', required=False)), ('chart_qualifier', wagtail.core.blocks.RichTextBlock(features=['h5', 'h6', 'ol', 'ul', 'bold', 'italic', 'hr', 'link'], help_text='Chart context e.g. legend, universe, etc.', label='Chart Qualifier', required=False)), ('chart_height', wagtail.core.blocks.IntegerBlock(help_text='Default is 300px', label='Chart Height', required=False)), ('widget_height', wagtail.core.blocks.IntegerBlock(help_text='Default is 450px', label='Widget Height', required=False))], icon='code', template='takwimu/_includes/dataview/hurumap.html')), ('entities', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text="This widget's tab label on the indicator", required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('hide_title', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('entities', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))]))), ('source', wagtail.core.blocks.RichTextBlock(features=['link'], required=False))], icon='group', template='takwimu/_includes/dataview/entities.html'))], required=False))], required=False))], required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='profilesectionpage',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='profilesectionpage',
            name='twitter_card',
            field=models.CharField(blank=True, choices=[('summary', 'Summary'), ('summary_large_image', 'Summary with image'), ('player', 'Media player'), ('app', 'Link to download app')], max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='facebook',
            field=models.URLField(blank=True, help_text='TAKWIMU Facebook page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='github',
            field=models.URLField(blank=True, help_text='TAKWIMU Github page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='instagram',
            field=models.URLField(blank=True, help_text='TAKWIMU Instagram account URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='linkedin',
            field=models.URLField(blank=True, help_text='TAKWIMU LinkedIn account URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='medium',
            field=models.URLField(blank=True, help_text='TAKWIMU Medium page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='twitter',
            field=models.URLField(blank=True, help_text='TAKWIMU Twitter account URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasetting',
            name='youtube',
            field=models.URLField(blank=True, help_text='TAKWIMU YouTube channel or account URL', null=True),
        ),
        migrations.AlterField(
            model_name='supportservicessetting',
            name='services',
            field=wagtail.core.fields.StreamField([('service', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('icon', takwimu.models.dashboard.IconChoiceBlock(required=False)), ('cover', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=True)), ('category', wagtail.core.blocks.ChoiceBlock(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Persona', 'Persona')], max_length=20))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='supportsetting',
            name='address',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='TAKWIMU address', null=True),
        ),
        migrations.AlterField(
            model_name='supportsetting',
            name='community',
            field=models.URLField(blank=True, help_text='TAKWIMU Community forums URL', null=True),
        ),
        migrations.AlterField(
            model_name='supportsetting',
            name='hello',
            field=models.EmailField(blank=True, help_text='TAKWIMU main email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supportsetting',
            name='support',
            field=models.EmailField(blank=True, help_text='TAKWIMU support email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supportsetting',
            name='zendesk',
            field=models.URLField(blank=True, help_text='TAKWIMU Zendesk account URL', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testimonials/'),
        ),
    ]
