# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 05:23
from django.db import migrations, models
import django.db.models.deletion
import meta.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0047_port_python_3_20190315_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('featured_analysis', wagtail.core.fields.StreamField([('featured_analysis', wagtail.core.blocks.StructBlock([('featured_page', wagtail.core.blocks.PageChooserBlock(target_model=['takwimu.ProfileSectionPage']))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(meta.models.ModelMeta, 'wagtailcore.page'),
        ),
    ]
