# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 14:53
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0047_port_python_3_20190315_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_analysis_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Analysis1', to='takwimu.ProfileSectionPage')),
                ('featured_analysis_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Analysis2', to='takwimu.ProfileSectionPage')),
                ('featured_analysis_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Analysis3', to='takwimu.ProfileSectionPage')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
