# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 12:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0047_port_python_3_20190315_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('featured_analysis_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Analysis1', to='takwimu.ProfileSectionPage')),
                ('featured_analysis_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Analysis2', to='takwimu.ProfileSectionPage')),
                ('featured_analysis_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Analysis3', to='takwimu.ProfileSectionPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
