# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 09:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0048_index_page_with_worldbank_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='latest_news_stories_description',
            field=models.CharField(default='Lorem ipsum dolor sit amet, adipiscing elitauris con lorem ipsum dolor sit amet.',
                                   max_length=1024, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='making_description',
            field=models.CharField(default='Lorem ipsum dolor sit amet, adipiscing elitauris con lorem ipsum dolor sit amet.',
                                   max_length=1024, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='tagline_description',
            field=models.CharField(
                default='Lorem ipsum dolor sit amet, adipiscing elitauris con', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='what_you_can_do_download',
            field=models.CharField(
                default='Lorem ipsum dolor sit amet, adipiscing elitauris con lorem ipsum dolor sit amet.', max_length=255, verbose_name='Download'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='what_you_can_do_present',
            field=models.CharField(
                default='Lorem ipsum dolor sit amet, adipiscing elitauris con lorem ipsum dolor sit amet.', max_length=255, verbose_name='Present'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='what_you_can_do_research',
            field=models.CharField(
                default='Lorem ipsum dolor sit amet, adipiscing elitauris con lorem ipsum dolor sit amet.', max_length=255, verbose_name='Research'),
        ),
    ]
