# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 13:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0050_aboutpagerelatedcontent_analysisrelatedcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrelatedcontent',
            name='page',
        ),
        migrations.AddField(
            model_name='profilesectionpage',
            name='analysis_related_content',
            field=wagtail.core.fields.StreamField([('analysis_related_content', wagtail.core.blocks.StructBlock([('analysis_related_content', wagtail.core.blocks.PageChooserBlock(target_model=['wagtailcore.Page']))]))], blank=True),
        ),
        migrations.DeleteModel(
            name='AnalysisRelatedContent',
        ),
    ]
