# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 14:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0051_auto_20190416_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagerelatedcontent',
            name='page',
        ),
        migrations.RemoveField(
            model_name='profilesectionpage',
            name='analysis_related_content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='related_content',
            field=wagtail.core.fields.StreamField([('related_content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('widgets', wagtail.core.blocks.StreamBlock([('free_form', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())])), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], required=False))], required=False))], blank=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='related_content',
            field=wagtail.core.fields.StreamField([('related_content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('widgets', wagtail.core.blocks.StreamBlock([('free_form', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())])), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], required=False))], required=False))], blank=True),
        ),
        migrations.AddField(
            model_name='profilesectionpage',
            name='related_content',
            field=wagtail.core.fields.StreamField([('related_content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('widgets', wagtail.core.blocks.StreamBlock([('free_form', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())])), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], required=False))], required=False))], blank=True),
        ),
        migrations.DeleteModel(
            name='AboutPageRelatedContent',
        ),
    ]
