# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 13:28
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0051_migrate_topic_to_freeform'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='methodology',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
