# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 14:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0052_auto_20190416_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='related_content',
            field=wagtail.core.fields.StreamField([('related_content', wagtail.core.blocks.StructBlock([('widgets', wagtail.core.blocks.StreamBlock([('free_form', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())], icon='snippet')), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], required=False))], required=False))], blank=True),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='related_content',
            field=wagtail.core.fields.StreamField([('related_content', wagtail.core.blocks.StructBlock([('widgets', wagtail.core.blocks.StreamBlock([('free_form', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())], icon='snippet')), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], required=False))], required=False))], blank=True),
        ),
        migrations.AlterField(
            model_name='profilesectionpage',
            name='related_content',
            field=wagtail.core.fields.StreamField([('related_content', wagtail.core.blocks.StructBlock([('widgets', wagtail.core.blocks.StreamBlock([('free_form', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())], icon='snippet')), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], required=False))], required=False))], blank=True),
        ),
    ]
