# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 15:12
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0057_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_analysis', wagtail.core.fields.RichTextField(default='<p>Lorem ipsum dolor sit amet, adipiscing elitauris con lorem ipsum dolor sit amet.</p>', verbose_name='description')),
                ('data_by_topic', wagtail.core.fields.RichTextField(default='<p>Lorem ipsum dolor sit amet, adipiscing elitauris con lorem ipsum dolor sit amet.</p>', verbose_name='description')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Navigation',
            },
        ),
    ]
