# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 07:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0057_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='related_content',
            field=wagtail.core.fields.StreamField([('related_content_links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Related Content', max_length=1024)), ('related_links', wagtail.core.blocks.StreamBlock([('related_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.StreamBlock([('url', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())], icon='link')), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], block_counts={'page': {'max_num': 1}, 'url': {'max_num': 1}}, max_num=1, min_num=1))]))], max_num=10))]))], blank=True),
        ),
    ]
