# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0059_featured_data_indicator_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_iso_code', models.CharField(choices=[('BF', 'Burkina Faso'), ('CD', 'Democratic Republic of Congo'), ('ET', 'Ethiopia'), ('KE', 'Kenya'), ('NG', 'Nigeria'), ('SN', 'Senegal'), ('ZA', 'South Africa'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('ZM', 'Zambia')], max_length=3, verbose_name='Country')),
                ('chart_id', models.CharField(max_length=1024, unique=True)),
                ('chart_title', models.CharField(max_length=1024)),
            ],
        ),
    ]
