# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 10:44
from django.db import migrations, models
import django.db.models.deletion
import meta.models
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
        ('takwimu', '0060_flourish_visuals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('address', wagtail.core.fields.RichTextField()),
                ('related_content', wagtail.core.fields.StreamField([('related_content_links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Related Content', max_length=1024)), ('related_links', wagtail.core.blocks.StreamBlock([('related_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.StreamBlock([('url', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())], icon='link')), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], block_counts={'page': {'max_num': 1}, 'url': {'max_num': 1}}, max_num=1, min_num=1))]))], max_num=10))]))], blank=True)),
                ('twitter_card', models.CharField(blank=True, choices=[('summary', 'Summary'), ('summary_large_image', 'Summary with image'), ('player', 'Media player'), ('app', 'Link to download app')], max_length=255)),
                ('tweet_creator', models.CharField(blank=True, max_length=255)),
                ('promotion_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(meta.models.ModelMeta, 'wagtailcore.page'),
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='url',
        ),
        migrations.AlterField(
            model_name='keycontacts',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_contacts', to='takwimu.ContactPage'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('medium', 'Medium'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='takwimu.ContactPage'),
        ),
        migrations.DeleteModel(
            name='ContactUsPage',
        ),
    ]
