# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import takwimu.models.dashboard
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0062_profiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('medium', 'Medium'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={},
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='page',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='social_media',
            field=wagtail.core.fields.StreamField([('social_media', wagtail.snippets.blocks.SnippetChooserBlock(takwimu.models.dashboard.SocialMedia))], blank=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=wagtail.core.fields.StreamField([('contact_address_content', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(default='Address', help_text='Short title used in navigation, etc.', max_length=255)), ('title', wagtail.core.blocks.CharBlock(default='Addresss', max_length=1024)), ('description', wagtail.core.blocks.RichTextBlock(default='<p>africapractice East Africa Ltd<br>P.O Box 40868 – 00100<br>Mitsumi Business Park, 7th Floor<br>Muthithi Road, Westlands</p>', required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='takwimu.SocialMedia'),
        ),
    ]
