# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0063_auto_20190520_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='label',
            field=models.CharField(default='Social', help_text='Short title used in navigation, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(default='Social', max_length=1024),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=wagtail.core.fields.StreamField([('contact_address_content', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(default='Address', help_text='Short title used in navigation, etc.', max_length=255)), ('title', wagtail.core.blocks.CharBlock(default='Addresss', max_length=1024)), ('description', wagtail.core.blocks.RichTextBlock(default='<p>africapractice East Africa Ltd<br/>P.O Box 40868 – 00100<br/>Mitsumi Business Park, 7th Floor<br/>Muthithi Road, Westlands</p>', required=False))]))], blank=True),
        ),
    ]
