# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import takwimu.models.dashboard
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0063_featureddata_flourish_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField()),
                ('contact_details', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('medium', 'Medium'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='keycontacts',
            options={'verbose_name': 'Contact Us | Key Contacts', 'verbose_name_plural': 'Contact Us | Key Contacts'},
        ),
        migrations.AlterModelOptions(
            name='profiledata',
            options={'verbose_name': 'Data by Topic | HURUmap Data', 'verbose_name_plural': 'Data by Topic | HURUmap Data'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Contact Us | Social Media', 'verbose_name_plural': 'Contact Us | Social Media'},
        ),
        migrations.RemoveField(
            model_name='keycontacts',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='keycontacts',
            name='link',
        ),
        migrations.RemoveField(
            model_name='keycontacts',
            name='page',
        ),
        migrations.RemoveField(
            model_name='keycontacts',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='page',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='key_contacts',
            field=wagtail.core.fields.StreamField([('key_contacts', wagtail.snippets.blocks.SnippetChooserBlock(takwimu.models.dashboard.KeyContacts))], blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='social_media',
            field=wagtail.core.fields.StreamField([('social_media', wagtail.snippets.blocks.SnippetChooserBlock(takwimu.models.dashboard.SocialMedia))], blank=True),
        ),
        migrations.AddField(
            model_name='keycontacts',
            name='label',
            field=models.CharField(default='Key contacts', help_text='Short title used in navigation, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='keycontacts',
            name='name',
            field=models.CharField(default='Default', help_text="If you're planning to maintain more than one list of contacts, then provide a unique name for this list", max_length=1024),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='label',
            field=models.CharField(default='Social', help_text='Short title used in navigation, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(default='Social', max_length=1024),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=wagtail.core.fields.StreamField([('contact_address_content', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(default='Address', help_text='Short title used in navigation, etc.', max_length=255)), ('title', wagtail.core.blocks.CharBlock(default='Address', max_length=1024)), ('description', wagtail.core.blocks.RichTextBlock(default='<p>africapractice East Africa Ltd<br/>P.O Box 40868 – 00100<br/>Mitsumi Business Park, 7th Floor<br/>Muthithi Road, Westlands</p><p></p><p>Nairobi, Kenya</p>', required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='keycontacts',
            name='title',
            field=models.CharField(default='Key contacts', max_length=1024),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(default='Default', help_text="If you're planning to maintain more than one list of contacts, then provide a unique name for this list", max_length=1024),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='takwimu.SocialMedia'),
        ),
        migrations.AddField(
            model_name='keycontact',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='takwimu.KeyContacts'),
        ),
    ]
