# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 14:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0064_auto_20190520_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Contact Us | Social Media', 'verbose_name_plural': 'Contact Us | Social Media'},
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=wagtail.core.fields.StreamField([('contact_address_content', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(default='Address', help_text='Short title used in navigation, etc.', max_length=255)), ('title', wagtail.core.blocks.CharBlock(default='Address', max_length=1024)), ('description', wagtail.core.blocks.RichTextBlock(default='<p>africapractice East Africa Ltd<br/>P.O Box 40868 – 00100<br/>Mitsumi Business Park, 7th Floor<br/>Muthithi Road, Westlands</p>', required=False))]))], blank=True),
        ),
    ]
