# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        # ('wazimap', '0013_port_to_python3'),
        ('takwimu', '0065_feedback_04'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataByTopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField()),
                ('country', models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wazimap.Geography')),
            ],
            options={
                'verbose_name': 'Data by Topic',
                'verbose_name_plural': 'Data by Topic',
            },
            bases=('wagtailcore.page',),
        ),
    ]
