# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 08:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0066_databytopicpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databytopicpage',
            options={'verbose_name': 'Data by Topic', 'verbose_name_plural': 'Data by Topic'},
        ),
        migrations.AlterField(
            model_name='databytopicpage',
            name='description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
