# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import meta.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
        ('takwimu', '0067_hurumapblock_number-stat-type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content_navigation_title', models.CharField(default='On this page', max_length=1024, verbose_name='title')),
                ('body', wagtail.core.fields.StreamField([('terms', wagtail.core.blocks.StreamBlock([('terms', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(default='Terms', help_text='Short title used in navigation, etc.', max_length=255)), ('title', wagtail.core.blocks.CharBlock(default='Terms of use', max_length=1024)), ('description', wagtail.core.blocks.RichTextBlock(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et lorem eros. Integer vel venenatis urna. Nam vestibulum felis vitae scelerisque imperdiet. Nulla nisl libero, vestibulum eu lorem at, consequat finibus libero. Ut tincidunt rutrum purus vitae interdum. Phasellus efficitur tincidunt lorem ut blandit.'))]))], max_num=1)), ('privacy_policy', wagtail.core.blocks.StreamBlock([('privacy', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(default='Privacy', help_text='Short title used in navigation, etc.', max_length=255)), ('title', wagtail.core.blocks.CharBlock(default='Privacy policy', max_length=1024)), ('description', wagtail.core.blocks.RichTextBlock(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et lorem eros. Integer vel venenatis urna. Nam vestibulum felis vitae scelerisque imperdiet. Nulla nisl libero, vestibulum eu lorem at, consequat finibus libero. Ut tincidunt rutrum purus vitae interdum. Phasellus efficitur tincidunt lorem ut blandit.'))]))], max_num=1))])),
                ('related_content', wagtail.core.fields.StreamField([('related_content_links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Related Content', max_length=1024)), ('related_links', wagtail.core.blocks.StreamBlock([('related_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.StreamBlock([('url', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock())], icon='link')), ('page', wagtail.core.blocks.PageChooserBlock(required=False))], block_counts={'page': {'max_num': 1}, 'url': {'max_num': 1}}, max_num=1, min_num=1))]))], max_num=10))]))], blank=True)),
                ('twitter_card', models.CharField(blank=True, choices=[('summary', 'Summary'), ('summary_large_image', 'Summary with image'), ('player', 'Media player'), ('app', 'Link to download app')], max_length=255)),
                ('tweet_creator', models.CharField(blank=True, max_length=255)),
                ('promotion_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(meta.models.ModelMeta, 'wagtailcore.page'),
        ),
    ]
