# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0067_auto_20190523_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databytopicpage',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.Geography', unique=True),
        ),
    ]
