# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takwimu', '0068_auto_20190523_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databytopicpage',
            name='country',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wazimap.Geography'),
        ),
    ]
